spring:
  datasource:
    url: ${SUPABASE_URL}
    username: ${SUPABASE_USERNAME}
    password: ${SUPABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  secret: ${SUPABASE_JWT_SECRET}