spring:
  datasource:
    url: ${SUPABASE_DB_URL}
    username: ${SUPABASE_DB_USERNAME}
    password: ${SUPABASE_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 15
      minimum-idle: 1
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: ${SPRING_FLYWAY_ENABLED:true}
    baseline-on-migrate: true

logging:
  level:
    com.zaxxer.hikari: INFO
    org.springframework.jdbc.datasource: INFO
    org.postgresql: INFO

jwt:
  secret: ${SUPABASE_JWT_SECRET:}
  expiration-ms: ${JWT_EXPIRATION_MS:3600000}

supabase:
  url: ${SUPABASE_REST_URL}
  key: ${SUPABASE_ANON_KEY}
